# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/user/application_security/sast/#available-cicd-variables
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure/
# Dependency Scanning customization: https://docs.gitlab.com/user/application_security/dependency_scanning/dependency_scanning_sbom/#customizing-analyzer-behavior
# Container Scanning customization: https://docs.gitlab.com/user/application_security/container_scanning/#customizing-analyzer-behavior
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ci/variables/#cicd-variable-precedence
stages:
- test
- secret-detection
- build

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
variables:
  SECRET_DETECTION_ENABLED: 'true'
secret_detection:
  stage: secret-detection

build-push:
  stage: build
  image: quay.io/podman/stable
  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes
  script:
    # Créer le manifest qui va contenir les deux architectures
    - podman manifest create $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

    # Build pour amd64 et arm64, ajoutés au même manifest
    - podman build --platform linux/amd64 --manifest $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - podman build --platform linux/arm64 --manifest $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .

    # Push le manifest avec le tag du commit
    - podman manifest push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

    # Tag aussi en "latest" et push
    - podman tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - podman manifest push $CI_REGISTRY_IMAGE:latest docker://$CI_REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'